from .document.doc_handler import DOC_Handler
from .document.docx_handler import DOCX_Handler
from .document.pdf_handler import PDF_Handler
from .image.jpg_handler import JPG_Handler
from .image.png_handler import PNG_Handler
from .presentation.pptx_handler import PPTX_Handler
from .table.xls_handler import XLS_Handler
from .table.xlsx_handler import XLSX_Handler
from .base import FileHandler
